### ISSUE TITLE
Broken with Python 3

### ISSUE THREAD

**Issue by kennethkalmer** [scrapy-plugins/scrapy-pagestorage#2]
I was trying to use this addon with the `scrapy:1.3-py3` stack and it blows up with the exception below.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/app/python/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1276, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 http://www.example.com/robots.txt>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/python/lib/python3.6/site-packages/scrapy/core/spidermw.py", line 42, in process_spider_input
    result = method(response=response, spider=spider)
  File "/usr/local/lib/python3.6/site-packages/scrapy_pagestorage.py", line 59, in process_spider_input
    self.save_response(response, spider)
  File "/usr/local/lib/python3.6/site-packages/scrapy_pagestorage.py", line 78, in save_response
    self._set_cookies(payload, response)
  File "/usr/local/lib/python3.6/site-packages/scrapy_pagestorage.py", line 110, in _set_cookies
    for x in response.headers.getlist('Set-Cookie')]:
  File "/usr/local/lib/python3.6/site-packages/scrapy_pagestorage.py", line 110, in <listcomp>
    for x in response.headers.getlist('Set-Cookie')]:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by jesuslosada** [comment]
This should work fine now that #5 has been merged into the master branch (0.2.2 release).

@vshlapakov I think this issue can be closed.
